DROP TABLE IF EXISTS USER_DEVICES_CUMULATED;

CREATE TABLE USER_DEVICES_CUMULATED (
    USER_ID NUMERIC
    , BROWSER_TYPE TEXT
    , DATE_LIST DATE[]
    , LOAD_DATE DATE
    , PRIMARY KEY(USER_ID, BROWSER_TYPE, LOAD_DATE)
);