@set DT_INFORMATION = '2023-01-01'

INSERT INTO USER_DEVICES_CUMULATED
WITH YESTERDAY AS (
SELECT
    USER_ID
    , BROWSER_TYPE
    , DATE_LIST
    , LOAD_DATE
FROM
    USER_DEVICES_CUMULATED
WHERE
	1 = 1
	AND LOAD_DATE = ${DT_INFORMATION}::DATE - INTERVAL '1 day'
), TODAY AS (
SELECT DISTINCT
    E.USER_ID
    , D.BROWSER_TYPE
    , ARRAY [
        E.EVENT_TIME::DATE
    ]::DATE[] AS DATE_LIST
FROM
    EVENTS AS E
    INNER JOIN
    DEVICES AS D
    ON (
        1 = 1
        AND E.DEVICE_ID = D.DEVICE_ID
    )
WHERE
    1 = 1
    AND E.USER_ID IS NOT NULL
	AND E.EVENT_TIME::DATE = ${DT_INFORMATION}
)
SELECT
    COALESCE(T.USER_ID, Y.USER_ID) AS USER_ID
    , COALESCE(T.BROWSER_TYPE, Y.BROWSER_TYPE) AS BROWSER_TYPE
    , CASE
        WHEN Y.USER_ID IS NULL THEN T.DATE_LIST -- FIRST INTERACTION ON BROWSER_TYPE
        WHEN Y.USER_ID IS NOT NULL THEN Y.DATE_LIST || T.DATE_LIST -- ALREADY INTERACTED IN THE PAST
        ELSE Y.DATE_LIST
    END AS DATE_LIST
    , ${DT_INFORMATION} AS LOAD_DATE
FROM
    TODAY AS T
    FULL OUTER JOIN
    YESTERDAY AS Y
    ON (
        T.USER_ID = Y.USER_ID
        AND T.BROWSER_TYPE = Y.BROWSER_TYPE
    );