WITH STARTER AS (
SELECT
    UDC.DATE_LIST @> ARRAY[D.VALID_DATE::DATE] AS IS_ACTIVE
    , EXTRACT (
        DAY FROM '2023-01-31'::DATE - D.VALID_DATE
    ) AS DAYS_SINCE
    , UDC.USER_ID
    , UDC.BROWSER_TYPE
FROM
    USER_DEVICES_CUMULATED AS UDC
    CROSS JOIN (
	    SELECT GENERATE_SERIES('2023-01-01', '2023-01-31', INTERVAL '1 DAY') AS VALID_DATE
    ) AS D
WHERE
    1 = 1
    AND UDC.LOAD_DATE = '2023-01-31'
)
SELECT
    USER_ID
    , BROWSER_TYPE
    , SUM (
        CASE
            WHEN IS_ACTIVE THEN POW(2, 32 - DAYS_SINCE)
            ELSE 0
        END
    )::BIGINT::BIT(32) AS DATELIST_INT
FROM
	STARTER
GROUP BY
    1, 2