@set DT_INFORMATION = '2023-01-01'

INSERT INTO HOSTS_CUMULATED
WITH YESTERDAY AS (
SELECT
    HOST
    , DATE_LIST
    , LOAD_DATE
FROM
    HOSTS_CUMULATED
WHERE
	1 = 1
	AND LOAD_DATE = ${DT_INFORMATION}::DATE - INTERVAL '1 day'
), TODAY AS (
SELECT DISTINCT
    E.HOST
    , ARRAY [
        E.EVENT_TIME::DATE
    ]::DATE[] AS DATE_LIST
FROM
    EVENTS AS E
WHERE
    1 = 1
	AND E.EVENT_TIME::DATE = ${DT_INFORMATION}
)
SELECT
    COALESCE(T.HOST, Y.HOST) AS HOST
    , CASE
        WHEN Y.HOST IS NULL THEN T.DATE_LIST -- FIRST INTERACTION ON BROWSER_TYPE
        WHEN Y.HOST IS NOT NULL THEN Y.DATE_LIST || T.DATE_LIST -- ALREADY INTERACTED IN THE PAST
        ELSE Y.DATE_LIST
    END AS DATE_LIST
    , ${DT_INFORMATION} AS LOAD_DATE
FROM
    TODAY AS T
    FULL OUTER JOIN
    YESTERDAY AS Y
    ON (
        T.HOST = Y.HOST
    );