DROP TABLE IF EXISTS HOST_ACTIVITY_REDUCED;

CREATE TABLE HOST_ACTIVITY_REDUCED (
    MONTH DATE
    , HOST TEXT
    , HIT_ARRAY INTEGER[]
    , UNIQUE_VISITORS_ARRAY INTEGER[]
    , PRIMARY KEY(MONTH, HOST)
);