@set DT_INFORMATION = '2023-01-01'

INSERT INTO HOST_ACTIVITY_REDUCED
WITH YESTERDAY AS (
SELECT
    MONTH
    , HOST
    , HIT_ARRAY
    , UNIQUE_VISITORS_ARRAY
FROM
    HOST_ACTIVITY_REDUCED
WHERE
	1 = 1
	AND MONTH = DATE_TRUNC('month', ${DT_INFORMATION}::DATE)::DATE
), TODAY AS (
SELECT
	DATE_TRUNC('month', EVENT_TIME::DATE)::DATE AS MONTH
	, HOST
	, ARRAY[COUNT(1)]::INT[] AS HIT_ARRAY
	, ARRAY[COUNT(DISTINCT USER_ID)]::INT[] AS UNIQUE_VISITORS_ARRAY
FROM EVENTS
WHERE
    1 = 1
	AND EVENT_TIME::DATE = ${DT_INFORMATION}
GROUP BY 1, 2
)
SELECT
    DATE_TRUNC('month', ${DT_INFORMATION}::DATE)::DATE AS MONTH
    , COALESCE(T.HOST, Y.HOST) AS HOST
    , CASE
        WHEN Y.HOST IS NULL THEN T.HIT_ARRAY -- FIRST INTERACTION ON BROWSER_TYPE
        WHEN Y.HOST IS NOT NULL THEN Y.HIT_ARRAY || T.HIT_ARRAY -- ALREADY INTERACTED IN THE PAST
        ELSE Y.HIT_ARRAY
    END AS HIT_ARRAY
    , CASE
        WHEN Y.HOST IS NULL THEN T.UNIQUE_VISITORS_ARRAY -- FIRST INTERACTION ON BROWSER_TYPE
        WHEN Y.HOST IS NOT NULL THEN Y.UNIQUE_VISITORS_ARRAY || T.UNIQUE_VISITORS_ARRAY -- ALREADY INTERACTED IN THE PAST
        ELSE Y.UNIQUE_VISITORS_ARRAY
    END AS UNIQUE_VISITORS_ARRAY
FROM
    TODAY AS T
    FULL OUTER JOIN
    YESTERDAY AS Y
    ON (
        T.HOST = Y.HOST
    )
ON CONFLICT (HOST, MONTH)
DO UPDATE SET HIT_ARRAY = EXCLUDED.HIT_ARRAY, UNIQUE_VISITORS_ARRAY = EXCLUDED.UNIQUE_VISITORS_ARRAY;