DROP TABLE IF EXISTS ACTORS;

DROP TYPE IF EXISTS FILMS;

CREATE TYPE FILMS AS (
    FILM TEXT
    , VOTES INTEGER
    , RATING REAL
    , FILMID TEXT
);

DROP TYPE IF EXISTS QUALITY_CLASS;

CREATE TYPE QUALITY_CLASS AS
ENUM (
    'star'
    , 'good'
    , 'average'
    , 'bad'
);


CREATE TABLE ACTORS (
    ACTORID TEXT
    , ACTOR TEXT
    , FILMS FILMS[]
    , QUALITY_CLASS QUALITY_CLASS
    , IS_ACTIVE BOOLEAN
    , CURRENT_YEAR INTEGER
    , PRIMARY KEY(ACTORID, CURRENT_YEAR)
);