DROP TABLE IF EXISTS ACTORS_HISTORY_SCD;

CREATE TABLE ACTORS_HISTORY_SCD (
    ACTORID TEXT
    , ACTOR TEXT
    , QUALITY_CLASS QUALITY_CLASS
    , IS_ACTIVE BOOLEAN
    , START_DATE INTEGER
    , END_DATE INTEGER
    , PRIMARY KEY(ACTORID, START_DATE)
);