INSERT INTO ACTORS_HISTORY_SCD
WITH PREVIOUS AS (
SELECT
    ACTORID
    , ACTOR
    , QUALITY_CLASS
    , LAG(QUALITY_CLASS, 1) OVER (
        PARTITION BY
            ACTORID
        ORDER BY
            CURRENT_YEAR
    ) AS PREVIOUS_QUALITY_CLASS
    , IS_ACTIVE
    , LAG(IS_ACTIVE, 1) OVER (
        PARTITION BY
            ACTORID
        ORDER BY
            CURRENT_YEAR
    ) AS PREVIOUS_IS_ACTIVE
    , CURRENT_YEAR
FROM
    ACTORS
), CHANGES AS (
SELECT
    ACTORID
    , ACTOR
    , QUALITY_CLASS
    , PREVIOUS_QUALITY_CLASS
    , IS_ACTIVE
    , PREVIOUS_IS_ACTIVE
    , CURRENT_YEAR
    , CASE
        WHEN QUALITY_CLASS <> PREVIOUS_QUALITY_CLASS THEN 1
        WHEN IS_ACTIVE <> PREVIOUS_IS_ACTIVE THEN 1
        ELSE 0
    END AS CHECK_CHANGES
FROM
    PREVIOUS
), STREAK AS (
SELECT
    ACTORID
    , ACTOR
    , QUALITY_CLASS
    , PREVIOUS_QUALITY_CLASS
    , IS_ACTIVE
    , PREVIOUS_IS_ACTIVE
    , CURRENT_YEAR
    , CHECK_CHANGES
    , SUM(CHECK_CHANGES) OVER (
        PARTITION BY
            ACTORID
        ORDER BY
            CURRENT_YEAR
    ) AS STREAK_SUM
FROM
    CHANGES
)
SELECT
    ACTORID
    , ACTOR
    , QUALITY_CLASS
    , IS_ACTIVE
    , MIN(CURRENT_YEAR) AS START_DATE
    , MAX(CURRENT_YEAR) AS END_DATE
FROM
    STREAK
GROUP BY
    ACTORID
    , ACTOR
    , QUALITY_CLASS
    , IS_ACTIVE
    , STREAK_SUM;