WITH DEDUPED_GAME_DETAILS AS (
SELECT
	ROW_NUMBER() OVER (
		PARTITION BY
			GD.GAME_ID
			, GD.TEAM_ID
			, GD.PLAYER_ID
	) AS RN
	, GD.GAME_ID
	, GD.PLAYER_NAME
	, GD.TEAM_ID
	, GD.TEAM_ABBREVIATION
	, COALESCE(GD.PTS, 0) AS PTS
	, CASE -- ADJUST FOR SEASON
        WHEN DATE_PART('MONTH', GAME_DATE_EST) >= 10 THEN DATE_PART('YEAR', GAME_DATE_EST)
        ELSE DATE_PART('YEAR', GAME_DATE_EST) - 1
    END AS SEASON
	, CASE
        WHEN G.HOME_TEAM_ID = GD.TEAM_ID THEN G.HOME_TEAM_WINS
        ELSE CASE
                WHEN G.HOME_TEAM_WINS = 0 THEN 1
                ELSE 0
            END
	END AS TEAM_WIN
	, G.GAME_DATE_EST
FROM
	GAME_DETAILS AS GD
	LEFT JOIN
	GAMES AS G
	ON (
		GD.GAME_ID = G.GAME_ID
	)
), TEAM_RESULTS AS (
-- REMOVE PLAYER GRANULARITY
SELECT
    GAME_ID
    , TEAM_ID
    , SEASON
    , MAX(TEAM_WIN) AS TEAM_WIN
FROM
    DEDUPED_GAME_DETAILS
WHERE
    1 = 1
    AND RN = 1
GROUP BY 1,2,3
), TEAM_WINS AS (
-- GET THE TOTAL WINS BY TEAM
SELECT
    TEAM_ID
    , SUM(TEAM_WIN) AS TOTAL_WINS
FROM
    TEAM_RESULTS
GROUP BY 1
), DATASET AS (
SELECT
	DGD.PLAYER_NAME
	, DGD.TEAM_ABBREVIATION
	, DGD.SEASON
	, SUM(DGD.PTS) AS TOTAL_POINTS
	, MAX(TR.TOTAL_WINS) AS TOTAL_WINS
    , GROUPING(DGD.PLAYER_NAME) AS G_PLAYER
    , GROUPING(DGD.TEAM_ABBREVIATION) AS G_TEAM
    , GROUPING(DGD.SEASON) AS G_SEASON
FROM
	DEDUPED_GAME_DETAILS AS DGD
	INNER JOIN
	TEAM_WINS AS TR
	ON (
		DGD.TEAM_ID = TR.TEAM_ID
	)
WHERE
	1 = 1
	AND DGD.RN = 1
GROUP BY GROUPING SETS (
	    (DGD.PLAYER_NAME, DGD.TEAM_ABBREVIATION) -- PLAYER + TEAM
	    , (DGD.PLAYER_NAME, DGD.SEASON) -- PLAYER + SEASON_YEAR
	    , (DGD.TEAM_ABBREVIATION) -- TEAM
	)
), ANSWERS_DATASET AS (
SELECT
    CASE
        WHEN g_player = 0 AND g_team = 0 AND g_season = 1 THEN 1
        WHEN g_player = 0 AND g_team = 1 AND g_season = 0 THEN 2
        WHEN g_player = 1 AND g_team = 0 AND g_season = 1 THEN 3
    END AS N_QUESTION
    , ROW_NUMBER() OVER (
        PARTITION BY
            G_PLAYER
            , G_TEAM
            , G_SEASON
        ORDER BY
            CASE
                WHEN G_PLAYER = 1 AND G_TEAM = 0 AND G_SEASON = 1 THEN TOTAL_WINS
                ELSE TOTAL_POINTS
            END DESC
    ) AS RN
    , *
FROM
    DATASET
)
SELECT
    CASE
        WHEN N_QUESTION = 1 THEN 'who scored the most points playing for one team?'
        WHEN N_QUESTION = 2 THEN 'who scored the most points in one season?'
        WHEN N_QUESTION = 3 THEN 'which team has won the most games?'
    END AS QUESTION
    , CASE
        WHEN N_QUESTION IN (1,2) THEN PLAYER_NAME
        WHEN N_QUESTION = 3 THEN TEAM_ABBREVIATION
    END AS ANSWER
    , CASE
        WHEN N_QUESTION IN (1,2) THEN TOTAL_POINTS
        WHEN N_QUESTION = 3 THEN TOTAL_WINS
    END AS VALS
FROM
    ANSWERS_DATASET
WHERE
    1 = 1
    AND RN = 1
;