-- What is the most games a team has won in a 90 game stretch?
WITH DATASET AS (
SELECT DISTINCT
    GD.GAME_ID
    , G.GAME_DATE_EST
    , GD.TEAM_ABBREVIATION
    , CASE
        WHEN G.HOME_TEAM_ID = GD.TEAM_ID THEN G.HOME_TEAM_WINS
        ELSE CASE WHEN G.HOME_TEAM_WINS = 0 THEN 1 ELSE 0 END
    END AS TEAM_WIN
FROM
    GAME_DETAILS GD
    LEFT JOIN
    GAMES AS G
    ON (
        GD.GAME_ID = G.GAME_ID
    )
), WINS_IN_90_GAMES AS (
SELECT
    TEAM_ABBREVIATION
    , SUM(TEAM_WIN) OVER (
        PARTITION BY
            TEAM_ABBREVIATION
        ORDER BY
            GAME_DATE_EST
        ROWS BETWEEN 89 PRECEDING AND CURRENT ROW
    ) AS WINS_IN_90_GAMES
FROM DATASET
)
SELECT
    TEAM_ABBREVIATION
    , MAX(WINS_IN_90_GAMES)
FROM
    WINS_IN_90_GAMES
GROUP BY 1
ORDER BY 2 DESC
FETCH FIRST 1 ROW WITH TIES
;

-- How many games in a row did LeBron James score over 10 points a game?
WITH DATASET AS (
SELECT
    GD.GAME_ID
    , G.GAME_DATE_EST
    , GD.TEAM_ABBREVIATION
    , GD.PLAYER_NAME
    , GD.PTS
    , CASE WHEN COALESCE(GD.PTS, 0) > 10 THEN 1 ELSE 0 END AS OVER_10
FROM
    GAME_DETAILS GD
    LEFT JOIN
    GAMES AS GTH
    ON (
	    GD.GAME_ID = GTH.GAME_ID
	    AND GD.TEAM_ID = GTH.HOME_TEAM_ID
    )
    LEFT JOIN
    GAMES AS G
    ON (
	    GD.GAME_ID = G.GAME_ID
    )
WHERE
	1 = 1
	AND GD.PLAYER_NAME = 'LeBron James'
), STREAK_GROUPS AS (
SELECT
    OVER_10
    , ROW_NUMBER() OVER (ORDER BY GAME_DATE_EST) - ROW_NUMBER() OVER (PARTITION BY OVER_10 ORDER BY GAME_DATE_EST) AS GRP
FROM
    DATASET
), STREAK_LENGTH AS (
SELECT
    GRP
    , COUNT(*) AS STREAK_LEN
FROM
    STREAK_GROUPS
WHERE
    1 = 1
    AND OVER_10 = 1
GROUP BY 1
)
SELECT
    MAX(STREAK_LEN)
FROM
    STREAK_LENGTH
;
